# App Name
spring.application.name=booking-system

# Database Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:bookingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console so we can view our tables in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in the console for easy debugging
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}